cockroach:
  dsn: "postgresql://root@cockroach1:26257/defaultdb?sslmode=disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "logs_raw"
  group_id: "log_consumer_group"

cassandra:
  hosts:
<<<<<<< HEAD
<<<<<<< Updated upstream
    - "cassandra1"
    - "cassandra2"
    - "cassandra3"
=======
    - "cassandra"
>>>>>>> Stashed changes
=======
    - "cassandra"
>>>>>>> c5ea2eb4ac1fe2a2bba4565c6779ac3f991786c5
  keyspace: "logks"

clickhouse:
  addr: "clickhouse:9000"
  username: "default"
  password: ""
  database: "default"

server:
  addr: "0.0.0.0:8000"
  port: 8000
