cockroach:
  dsn: "postgresql://root@cockroach1:26257/defaultdb?sslmode=disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "logs_raw"
  group_id: "log_consumer_group"

cassandra:
  hosts:
    - "cassandra"

clickhouse:
  addr: "clickhouse:9000"
  username: "default"
  password: ""
  database: "default"

server:
  addr: "0.0.0.0:8000"
  port: 8000
